language: php
sudo: true
dist: trusty

env:
  global:
    - RUN_PHPCS="no"
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
    - php: 5.3
      dist: precise
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: RUN_PHPCS="yes"
    - php: 7.0
    - php: 7.0
      # This empty flag removes the prefer-stable switch to cause dev dependencies to be installed
      env: COMPOSER_FLAGS=""
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: 7.2
    - php: nightly

#before_install:
#  - sh -e .travis/scripts/apt-get.sh
#  - sh -e .travis/scripts/apache2-vhost.sh
#  - sh -e .travis/scripts/apache2-configure.sh

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart

before_script:
  - composer self-update
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --configuration phpunit.travis.xml
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards && vendor/bin/phpcs -p --report=full --extensions=php --standard=Joomla src/; fi;
